// actions PESSOA FISICA e PESSOA JURIDICA
export const EXECUTANDO_TAREFA_PESSOAS = 'EXECUTANDO_TAREFA_PESSOAS';
export const ERRO_PESSOAS = 'ERRO_PESSOAS';
export const SUCESSO_PESSOAS = 'SUCESSO_PESSOAS';
export const FILTRAR_PESSOAS = 'FILTRAR_PESSOAS';
export const FETCH_ALL_PESSOAS = 'FETCH_ALL_PESSOAS';
export const RESET_STATES_PESSOA = 'RESET_STATES_PESSOA';

// actions ESTADO e CIDADE
export const EXECUTANDO_TAREFA_ENDERECO = 'EXECUTANDO_TAREFA_ENDERECO';
export const ERRO_ENDERECO = 'ERRO_ENDERECO';
export const FETCH_ALL_CIDADE_ESTADO = 'FETCH_ALL_CIDADE_ESTADO';
export const FETCH_ALL_PAISES = 'FETCH_ALL_PAISES';

// actions USUARIO
export const EXECUTANDO_TAREFA_USUARIOS = 'EXECUTANDO_TAREFA_USUARIOS';
export const ERRO_USUARIOS = 'ERRO_USUARIOS';
export const SUCESSO_USUARIOS = 'SUCESSO_USUARIOS';
export const FILTRAR_USUARIOS = 'FILTRAR_USUARIOS';
export const FETCH_ALL_USUARIOS = 'FETCH_ALL_USUARIOS';
export const RESET_STATES_USUARIO = 'RESET_STATES_USUARIO';

// actions PERFIL
export const FETCH_PERFIS = 'FETCH_PERFIS';
export const RESET_PERFIS = 'RESET_PERFIS';

// actions TIPOS_DISPOSITIVO
export const EXECUTANDO_TAREFA_TIPOS_DISPOSITIVOS = 'EXECUTANDO_TAREFA_TIPOS_DISPOSITIVOS';
export const ERRO_TIPOS_DISPOSITIVOS = 'ERRO_TIPOS_DISPOSITIVOS';
export const SUCESSO_TIPOS_DISPOSITIVOS = 'SUCESSO_TIPOS_DISPOSITIVOS';
export const FILTRAR_TIPOS_DISPOSITIVOS = 'FILTRAR_TIPOS_DISPOSITIVOS';
export const FETCH_ALL_TIPOS_DISPOSITIVOS = 'FETCH_ALL_TIPOS_DISPOSITIVOS';
export const RESET_STATES_TIPO_DISPOSITIVO = 'RESET_STATES_TIPO_DISPOSITIVO';

// actions BOMBA
export const EXECUTANDO_TAREFA_BOMBAS = 'EXECUTANDO_TAREFA_BOMBAS';
export const ERRO_BOMBAS = 'ERRO_BOMBAS';
export const SUCESSO_BOMBAS = 'SUCESSO_BOMBAS';
export const FILTRAR_BOMBAS = 'FILTRAR_BOMBAS';
export const FETCH_ALL_BOMBAS = 'FETCH_ALL_BOMBAS';
export const RESET_STATES_BOMBA = 'RESET_STATES_BOMBA';

// actions BOMBA
export const EXECUTANDO_TAREFA_TIPOS_BOMBAS = 'EXECUTANDO_TAREFA_TIPOS_BOMBAS';
export const ERRO_TIPOS_BOMBAS = 'ERRO_TIPOS_BOMBAS';
export const SUCESSO_TIPOS_BOMBAS = 'SUCESSO_TIPOS_BOMBAS';
export const FILTRAR_TIPOS_BOMBAS = 'FILTRAR_TIPOS_BOMBAS';
export const FETCH_ALL_TIPOS_BOMBAS = 'FETCH_ALL_TIPOS_BOMBAS';
export const RESET_STATES_TIPO_BOMBA = 'RESET_STATES_TIPO_BOMBA';

// actions CONTRATO
export const EXECUTANDO_TAREFA_CONTRATOS = 'EXECUTANDO_TAREFA_CONTRATOS';
export const FETCH_ALL_CONTRATOS = 'FETCH_ALL_CONTRATOS';
export const ERRO_CONTRATOS = 'ERRO_CONTRATOS';
export const SUCESSO_CONTRATOS = 'SUCESSO_CONTRATOS';
export const FILTRAR_CONTRATOS = 'FILTRAR_CONTRATOS';
export const RESET_STATES_CONTRATOS = 'RESET_STATES_CONTRATOS';

// actions DISPOSITIVOS
export const RESET_STATES_DISPOSITIVO = 'RESET_STATES_DISPOSITIVO';

// actions FABRICANTE DISPOSITIVO
export const EXECUTANDO_TAREFA_FABRICANTES_DISPOSITIVOS = 'EXECUTANDO_TAREFA_FABRICANTES_DISPOSITIVOS';
export const ERRO_FABRICANTES_DISPOSITIVOS = 'ERRO_FABRICANTES_DISPOSITIVOS';
export const SUCESSO_FABRICANTES_DISPOSITIVOS = 'SUCESSO_FABRICANTES_DISPOSITIVOS';
export const FILTRAR_FABRICANTES_DISPOSITIVOS = 'FILTRAR_FABRICANTES_DISPOSITIVOS';
export const FETCH_ALL_FABRICANTES_DISPOSITIVOS = 'FETCH_ALL_FABRICANTES_DISPOSITIVOS';
export const RESET_STATES_FABRICANTE_DISPOSITIVO = 'RESET_STATES_FABRICANTE_DISPOSITIVO';

// actions MODELO DISPOSITIVO
export const EXECUTANDO_TAREFA_MODELOS_DISPOSITIVOS = 'EXECUTANDO_TAREFA_MODELOS_DISPOSITIVOS';
export const ERRO_MODELOS_DISPOSITIVOS = 'ERRO_MODELOS_DISPOSITIVOS';
export const SUCESSO_MODELOS_DISPOSITIVOS = 'SUCESSO_MODELOS_DISPOSITIVOS';
export const FILTRAR_MODELOS_DISPOSITIVOS = 'FILTRAR_MODELOS_DISPOSITIVOS';
export const FETCH_ALL_MODELOS_DISPOSITIVOS = 'FETCH_ALL_MODELOS_DISPOSITIVOS';
export const RESET_STATES_MODELO_DISPOSITIVO = 'RESET_STATES_MODELO_DISPOSITIVO';

// actions FABRICANTE EQUIPAMENTO
export const EXECUTANDO_TAREFA_FABRICANTES_EQUIPAMENTOS = 'EXECUTANDO_TAREFA_FABRICANTES_EQUIPAMENTOS';
export const ERRO_FABRICANTES_EQUIPAMENTOS = 'ERRO_FABRICANTES_EQUIPAMENTOS';
export const SUCESSO_FABRICANTES_EQUIPAMENTOS = 'SUCESSO_FABRICANTES_EQUIPAMENTOS';
export const FILTRAR_FABRICANTES_EQUIPAMENTOS = 'FILTRAR_FABRICANTES_EQUIPAMENTOS';
export const FETCH_ALL_FABRICANTES_EQUIPAMENTOS = 'FETCH_ALL_FABRICANTES_EQUIPAMENTOS';
export const RESET_STATES_FABRICANTE_EQUIPAMENTO = 'RESET_STATES_FABRICANTE_EQUIPAMENTO';

// actions MODELO DISPOSITIVO
export const EXECUTANDO_TAREFA_MODELOS_EQUIPAMENTOS = 'EXECUTANDO_TAREFA_MODELOS_EQUIPAMENTOS';
export const ERRO_MODELOS_EQUIPAMENTOS = 'ERRO_MODELOS_EQUIPAMENTOS';
export const SUCESSO_MODELOS_EQUIPAMENTOS = 'SUCESSO_MODELOS_EQUIPAMENTOS';
export const FILTRAR_MODELOS_EQUIPAMENTOS = 'FILTRAR_MODELOS_EQUIPAMENTOS';
export const FETCH_ALL_MODELOS_EQUIPAMENTOS = 'FETCH_ALL_MODELOS_EQUIPAMENTOS';
export const RESET_STATES_MODELO_EQUIPAMENTO = 'RESET_STATES_MODELO_EQUIPAMENTO';

// actions CONTAINER
export const EXECUTANDO_TAREFA_TIPOS_CONTAINERS = 'EXECUTANDO_TAREFA_TIPOS_CONTAINERS';
export const ERRO_TIPOS_CONTAINERS = 'ERRO_TIPOS_CONTAINERS';
export const SUCESSO_TIPOS_CONTAINERS = 'SUCESSO_TIPOS_CONTAINERS';
export const FILTRAR_TIPOS_CONTAINERS = 'FILTRAR_TIPOS_CONTAINERS';
export const FETCH_ALL_TIPOS_CONTAINERS = 'FETCH_ALL_TIPOS_CONTAINERS';
export const RESET_STATES_TIPO_CONTAINER = 'RESET_STATES_TIPO_CONTAINER';

// actions COMPARTIMENTO
export const EXECUTANDO_TAREFA_TIPOS_COMPARTIMENTOS = 'EXECUTANDO_TAREFA_TIPOS_COMPARTIMENTOS';
export const ERRO_TIPOS_COMPARTIMENTOS = 'ERRO_TIPOS_COMPARTIMENTOS';
export const SUCESSO_TIPOS_COMPARTIMENTOS = 'SUCESSO_TIPOS_COMPARTIMENTOS';
export const FILTRAR_TIPOS_COMPARTIMENTOS = 'FILTRAR_TIPOS_COMPARTIMENTOS';
export const FETCH_ALL_TIPOS_COMPARTIMENTOS = 'FETCH_ALL_TIPOS_COMPARTIMENTOS';
export const RESET_STATES_TIPO_COMPARTIMENTO = 'RESET_STATES_TIPO_COMPARTIMENTO';

// actions VINCULADO
export const EXECUTANDO_TAREFA_VINCULADOS = 'EXECUTANDO_TAREFA_VINCULADOS';
export const ERRO_VINCULADOS = 'ERRO_VINCULADOS';
export const SUCESSO_VINCULADOS = 'SUCESSO_VINCULADOS';
export const FILTRAR_VINCULADOS = 'FILTRAR_VINCULADOS';
export const FETCH_ALL_VINCULADOS = 'FETCH_ALL_VINCULADOS';
export const RESET_STATES_VINCULADO = 'RESET_STATES_VINCULADO';

export const ERRO_VINCULADOS_PESSOA_FISICA = 'ERRO_VINCULADOS_PESSOA_FISICA';
export const EXECUTANDO_TAREFA_VINCULADOS_PESSOA_FISICA = 'EXECUTANDO_TAREFA_VINCULADOS_PESSOA_FISICA';
export const FETCH_ALL_VINCULADOS_PESSOA_FISICA='FETCH_ALL_VINCULADOS_PESSOA_FISICA';

export const ERRO_VINCULADOS_NATUREZA = 'ERRO_VINCULADOS_NATUREZA';
export const EXECUTANDO_TAREFA_VINCULADOS_NATUREZA = 'EXECUTANDO_TAREFA_VINCULADOS_NATUREZA';
export const FETCH_ALL_VINCULADOS_NATUREZA='FETCH_ALL_VINCULADOS_NATUREZA';

export const ERRO_VINCULADOS_PROFISSAO = 'ERRO_VINCULADOS_PROFISSAO';
export const EXECUTANDO_TAREFA_VINCULADOS_PROFISSAO = 'EXECUTANDO_TAREFA_VINCULADOS_PROFISSAO';
export const FETCH_ALL_VINCULADOS_PROFISSAO='FETCH_ALL_VINCULADOS_PROFISSAO';

// actions Localização físca
export const EXECUTANDO_TAREFA_LOCALIZACAO_FISICA = 'EXECUTANDO_TAREFA_LOCALIZACAO_FISICA';
export const ERRO_LOCALIZACAO_FISICA = 'ERRO_LOCALIZACAO_FISICA';
export const FETCH_ALL_LOCALIZACAO_FISICA = 'FETCH_ALL_LOCALIZACAO_FISICA';
export const FILTRAR_LOCALIZACAO_FISICA = 'FILTRAR_LOCALIZACAO_FISICA';
export const SUCESSO_LOCALIZACAO_FISICA = 'SUCESSO_LOCALIZACAO_FISICA';
export const RESET_LOCALIZACAO_FISICA = 'RESET_LOCALIZACAO_FISICA';

export const EXECUTANDO_TAREFA_LOCALIZACAO_PESSOA_JURIDICA = 'EXECUTANDO_TAREFA_LOCALIZACAO_PESSOA_JURIDICA';
export const FILTRAR_LOCALIZACAO_JURIDICA = 'FILTRAR_LOCALIZACAO_JURIDICA';
export const FETCH_ALL_LOCALIZACAO_PESSOA_JURIDICA = 'FETCH_ALL_LOCALIZACAO_PESSOA_JURIDICA';
export const ERRO_LOCALIZACAO_PESSOA_JURIDICA = 'ERRO_LOCALIZACAO_PESSOA_JURIDICA';
export const RESET_LOCALIZACAO_JURIDICA = 'RESET_LOCALIZACAO_JURIDICA';

// actions Compartimentos
export const EXECUTANDO_TAREFA_COMPARTIMENTOS = 'EXECUTANDO_TAREFA_COMPARTIMENTOS';
export const ERRO_COMPARTIMENTOS = 'ERRO_COMPARTIMENTOS';
export const FETCH_ALL_COMPARTIMENTOS = 'FETCH_ALL_COMPARTIMENTOS';
export const FILTRAR_COMPARTIMENTOS = 'FILTRAR_COMPARTIMENTOS';
export const SUCESSO_COMPARTIMENTOS = 'SUCESSO_COMPARTIMENTOS';
export const RESET_COMPARTIMENTOS = 'RESET_COMPARTIMENTOS';
export const FETCH_ALL_COMPARTIMENTOS_LOCALIZACAO = 'FETCH_ALL_COMPARTIMENTOS_LOCALIZACAO';

// actions Compartimentos
export const EXECUTANDO_TAREFA_CONTAINERS = 'EXECUTANDO_TAREFA_CONTAINERS';
export const ERRO_CONTAINERS = 'ERRO_CONTAINERS';
export const FETCH_ALL_CONTAINERS = 'FETCH_ALL_CONTAINERS';
export const FILTRAR_CONTAINERS = 'FILTRAR_CONTAINERS';
export const SUCESSO_CONTAINERS = 'SUCESSO_CONTAINERS';
export const RESET_CONTAINERS = 'RESET_CONTAINERS';
export const FETCH_ALL_CONTAINERS_LOCALIZACAO = 'FETCH_ALL_CONTAINERS_LOCALIZACAO';

// actions FABRICANTE DISPOSITIVO
export const EXECUTANDO_TAREFA_GRUPOS_PESSOAS_JURIDICAS = 'EXECUTANDO_TAREFA_GRUPOS_PESSOAS_JURIDICAS';
export const ERRO_GRUPOS_PESSOAS_JURIDICAS = 'ERRO_GRUPOS_PESSOAS_JURIDICAS';
export const SUCESSO_GRUPOS_PESSOAS_JURIDICAS = 'SUCESSO_GRUPOS_PESSOAS_JURIDICAS';
export const FILTRAR_GRUPOS_PESSOAS_JURIDICAS = 'FILTRAR_GRUPOS_PESSOAS_JURIDICAS';
export const FETCH_ALL_GRUPOS_PESSOAS_JURIDICAS = 'FETCH_ALL_GRUPOS_PESSOAS_JURIDICAS';
export const RESET_STATES_GRUPO_PESSOAS_JURIDICAS = 'RESET_STATES_GRUPO_PESSOAS_JURIDICAS';

// actions NOTAS FISCAIS COMPRA
export const EXECUTANDO_TAREFA_NOTAS_FISCAIS_COMPRA = 'EXECUTANDO_TAREFA_NOTAS_FISCAIS_COMPRA';
export const ERRO_NOTAS_FISCAIS_COMPRA = 'ERRO_NOTAS_FISCAIS_COMPRA';
export const SUCESSO_NOTAS_FISCAIS_COMPRA = 'SUCESSO_NOTAS_FISCAIS_COMPRA';
export const FILTRAR_NOTAS_FISCAIS_COMPRA = 'FILTRAR_NOTAS_FISCAIS_COMPRA';
export const FETCH_ALL_NOTAS_FISCAIS_COMPRA = 'FETCH_ALL_NOTAS_FISCAIS_COMPRA';
export const RESET_STATES_NOTA_FISCAL_COMPRA = 'RESET_STATES_NOTA_FISCAL_COMPRA';

// actions TIPOS_INSUMO
export const EXECUTANDO_TAREFA_TIPOS_INSUMOS = 'EXECUTANDO_TAREFA_TIPOS_INSUMOS';
export const ERRO_TIPOS_INSUMOS = 'ERRO_TIPOS_INSUMOS';
export const SUCESSO_TIPOS_INSUMOS = 'SUCESSO_TIPOS_INSUMOS';
export const FILTRAR_TIPOS_INSUMOS = 'FILTRAR_TIPOS_INSUMOS';
export const FETCH_ALL_TIPOS_INSUMOS = 'FETCH_ALL_TIPOS_INSUMOS';
export const RESET_STATES_TIPO_INSUMO = 'RESET_STATES_TIPO_INSUMO';

// actions ORDEM PRODUCAO
export const EXECUTANDO_TAREFA_ORDEM_PRODUCAO = 'EXECUTANDO_TAREFA_ORDEM_PRODUCAO';
export const ERRO_ORDEM_PRODUCAO = 'ERRO_ORDEM_PRODUCAO';
export const SUCESSO_ORDEM_PRODUCAO = 'SUCESSO_ORDEM_PRODUCAO';
export const FILTRAR_ORDEM_PRODUCAO = 'FILTRAR_ORDEM_PRODUCAO';
export const FETCH_ALL_ORDEM_PRODUCAO = 'FETCH_ALL_ORDEM_PRODUCAO';
export const RESET_STATES_ORDEM_PRODUCAO = 'RESET_STATES_ORDEM_PRODUCAO';

// actions FATURA
export const EXECUTANDO_TAREFA_FATURAS = 'EXECUTANDO_TAREFA_FATURAS';
export const FETCH_ALL_FATURAS = 'FETCH_ALL_FATURAS';
export const ERRO_FATURAS = 'ERRO_FATURAS';
export const FILTRAR_FATURAS = 'FILTRAR_FATURAS';
export const SUCESSO_FATURAS = 'SUCESSO_FATURAS';
export const RESET_STATES_FATURAS = 'RESET_STATES_FATURAS';

// actions MANUTENCAO
export const EXECUTANDO_TAREFA_MANUTENCAO = 'EXECUTANDO_TAREFA_MANUTENCAO';
export const ERRO_MANUTENCAO = 'ERRO_MANUTENCAO';
export const SUCESSO_MANUTENCAO = 'SUCESSO_MANUTENCAO';
export const FILTRAR_MANUTENCAO = 'FILTRAR_MANUTENCAO';
export const FETCH_ALL_MANUTENCAO = 'FETCH_ALL_MANUTENCAO';
export const RESET_STATES_MANUTENCAO = 'RESET_STATES_MANUTENCAO';